title: Arbyte
email: arun.electrosoft@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Arbyte is an AI-powered embedded systems academy offering practical training in embedded systems,
  automotive software, Linux, AI, Zephyr RTOS, Raspberry Pi, and Edge AI.
baseurl: ""
url: "https://arunelectrosoft.github.io/"
github_username:  arunelectrosoft
lang: en
logo: /assets/images/brandicon.png
markdown: kramdown

kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5

collections_dir: siteContents
collections:
  Courses:
    output: true
    permalink: /courses/:path.html
  Demos:
    output: true
    permalink: /demos/:path.html
  Blog:
    output: true
    permalink: /blog/:path.html
  About:
    output: true
    permalink: /about/:path.html
  Contact:
    output: true
    permalink: /contact/:path.html
  Solutions:
    output: false
    permalink: /solutions/:path.html

exclude:
  - .github
  - .jekyll-cache
  - .jekyll-metadata
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tests

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: assets
  style: compressed

theme: jekyll-theme-slate
